name: Pull Request Labeler

on:
  pull_request:
    types:
      - opened

jobs:
  label_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Check Environment and Label PR
      id: label
      run: |
        PR_BODY=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r '.body')
        
        if [[ $PR_BODY == *"Environment: Development"* ]]; then
          echo "Labeling PR as 'Development'"
          echo "::set-output name=LABEL::Development"
        elif [[ $PR_BODY == *"Environment: Testing"* ]]; then
          echo "Labeling PR as 'Testing'"
          echo "::set-output name=LABEL::Testing"
        elif [[ $PR_BODY == *"Environment: Production"* ]]; then
          echo "Labeling PR as 'Production'"
          echo "::set-output name=LABEL::Production"
        else
          echo "No environment label found in the PR description."
          echo "::set-output name=LABEL::"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Apply Label to PR
      if: steps.label.outputs.LABEL != ''
      run: |
        LABEL=${{ steps.label.outputs.LABEL }}
        echo "Applying the label '$LABEL' to the PR."
        echo "::add-labels::$LABEL"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
