CREATE TABLE admin
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name         VARCHAR(255),
    username          VARCHAR(255),
    email             VARCHAR(255),
    password          VARCHAR(255),
    user_type         SMALLINT,
    verification_code BIGINT,
    CONSTRAINT pk_admin PRIMARY KEY (id)
);

CREATE TABLE cart
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT,
    total_price    DOUBLE PRECISION,
    total_discount DOUBLE PRECISION,
    total_shipping DOUBLE PRECISION,
    total_amount   DOUBLE PRECISION,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE customer
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name    VARCHAR(255),
    username     VARCHAR(255),
    email        VARCHAR(255),
    password     VARCHAR(255),
    user_type    SMALLINT,
    address      VARCHAR(255),
    phone_number VARCHAR(255),
    city         VARCHAR(255),
    country      VARCHAR(255),
    zip_code     VARCHAR(255),
    state        VARCHAR(255),
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE eorder
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_date       TIMESTAMP WITHOUT TIME ZONE,
    status           VARCHAR(255),
    shipping_address VARCHAR(255),
    payment_method   VARCHAR(255),
    total_amount     DOUBLE PRECISION,
    CONSTRAINT pk_eorder PRIMARY KEY (id)
);

CREATE TABLE order_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT,
    order_id   BIGINT,
    quantity   INTEGER,
    price      DOUBLE PRECISION,
    total      DOUBLE PRECISION,
    CONSTRAINT pk_orderitem PRIMARY KEY (id)
);

CREATE TABLE payment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id       BIGINT                                  NOT NULL,
    payment_date   TIMESTAMP WITHOUT TIME ZONE,
    payment_status VARCHAR(255),
    payment_method VARCHAR(255),
    amount         DOUBLE PRECISION,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

CREATE TABLE product
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    price    DOUBLE PRECISION                        NOT NULL,
    category VARCHAR(255),
    quantity INTEGER                                 NOT NULL,
    cart_id  BIGINT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE review
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id  BIGINT,
    customer_id BIGINT                                  NOT NULL,
    title       VARCHAR(255),
    rating      INTEGER,
    comment     VARCHAR(255),
    review_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_review PRIMARY KEY (id)
);

CREATE TABLE seller
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name            VARCHAR(255),
    username             VARCHAR(255),
    email                VARCHAR(255),
    password             VARCHAR(255),
    user_type            SMALLINT,
    company_name         VARCHAR(255),
    company_address      VARCHAR(255),
    company_phone_number VARCHAR(255),
    CONSTRAINT pk_seller PRIMARY KEY (id)
);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDERITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES eorder (id);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDERITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE payment
    ADD CONSTRAINT FK_ORDER_ID FOREIGN KEY (order_id) REFERENCES eorder (id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);