version: 2.1

executors:
  default-executor:
    docker:
      - image: circleci/openjdk:17

jobs:
  build:
    executor: default-executor

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y maven

      - run:
          name: Build and Test
          command: mvn clean install

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
