name: Stale Issue and PR Management

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule to run daily

jobs:
  stale_management:
    runs-on: ubuntu-latest

    steps:
      - name: Check Stale Issues and PRs
        uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30  # Define the number of days before an issue or PR is considered stale
